<?xml version="1.0" encoding="utf-8"?><Database Name="MIS442_SMusgrave" Class="MIS442DBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=turnsol.arvixe.com;Initial Catalog=MIS442_SMusgrave;Persist Security Info=True;User ID=smusgrave" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="MIS442_SMusgraveConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="SMusgrave.sp_Product_Get" Method="sp_Product_Get">
    <Parameter Name="ProductID" Parameter="productID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_Product_GetResult">
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="SMusgrave.sp_Product_GetList" Method="sp_Product_GetList">
    <ElementType Name="sp_Product_GetListResult">
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductCode" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ProductVersion" Type="System.Decimal" DbType="Decimal(5,1) NOT NULL" CanBeNull="false" />
      <Column Name="ProductReleaseDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="SMusgrave.sp_Product_InsertUpdate" Method="sp_Product_InsertUpdate">
    <Parameter Name="ProductID" Parameter="productID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ProductCode" Parameter="productCode" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="ProductName" Parameter="productName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ProductVersion" Parameter="productVersion" Type="System.Decimal" DbType="Decimal(5,1)" />
    <Parameter Name="ProductReleaseDate" Parameter="productReleaseDate" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
</Database>